"""initial schema

Revision ID: 96588aa65d2d
Revises: 
Create Date: 2026-08-13 15:02:36.151798

"""
from alembic import op
import sqlalchemy as sa


revision = '96588aa65d2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('monthly_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_snapshots_month'), ['month'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('current_carry_balance', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_no', 'name', name='uq_person_key')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_personal_no'), ['personal_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_status'), ['status'], unique=False)

    op.create_table('balance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('carry_balance', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('usage', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['monthly_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'person_id', name='uq_snapshot_person')
    )
    with op.batch_alter_table('balance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_records_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_records_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_records_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_balance_records_person_id'))

    op.drop_table('balance_records')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_status'))
        batch_op.drop_index(batch_op.f('ix_people_personal_no'))

    op.drop_table('people')
    op.drop_table('teams')
    with op.batch_alter_table('monthly_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_snapshots_month'))

    op.drop_table('monthly_snapshots')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
